version: '3.9'

services:
  api:
    build: .
    ports:
      - "80:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://rishabh:${DB_PASSWORD}@db:5432/cloud_vault
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=HS256
      - STORAGE_DIR=/app/storage/Files/
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-credentials.json
    volumes:
      - ./gcp-credentials.json:/app/gcp-credentials.json:ro
    restart: unless-stopped

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=rishabh
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=cloud_vault
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: