"""Auth Tables

Revision ID: 040ce05fa093
Revises: ecac7ad70e6c
Create Date: 2025-07-15 09:29:16.536144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '040ce05fa093'
down_revision: Union[str, Sequence[str], None] = 'ecac7ad70e6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('user_id', sa.Uuid(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'user_id')
    # ### end Alembic commands ###
