"""Auth Tables

Revision ID: ba3d72468f06
Revises: ee9b14a46e9d
Create Date: 2025-07-14 16:06:23.243556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ba3d72468f06'
down_revision: Union[str, Sequence[str], None] = 'ee9b14a46e9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('users', 'auth_proivder')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_proivder', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'auth_provider')
    # ### end Alembic commands ###
