"""added cloud

Revision ID: dfc1a2b0741f
Revises: 040ce05fa093
Create Date: 2025-07-17 22:00:32.427119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dfc1a2b0741f'
down_revision: Union[str, Sequence[str], None] = '040ce05fa093'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('confirmation', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'confirmation')
    # ### end Alembic commands ###
