"""Auth Tables

Revision ID: ecac7ad70e6c
Revises: cfb0e9f15926
Create Date: 2025-07-14 22:15:02.694849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ecac7ad70e6c'
down_revision: Union[str, Sequence[str], None] = 'cfb0e9f15926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('family_id', sa.Uuid(), nullable=False))
    op.add_column('refresh_tokens', sa.Column('previous_token_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'previous_token_id')
    op.drop_column('refresh_tokens', 'family_id')
    # ### end Alembic commands ###
